name: Send updates dev

on:
  workflow_dispatch:
  # push:
  #   branches: ['main']
  # push:
  #   branches: ['master']

jobs:
  send_updates:
    name: Send updates
    type: update
    params:
      channel: development
