name: Send updates

on:
  workflow_dispatch:
  # push:
  #   branches: ['main']
  # push:
  #   branches: ['master']

jobs:
  send_updates:
    name: Send updates prod
    type: update
    params:
      channel: production
