import { internalMutation } from "../_generated/server";
import { seriesTestHelpers } from "./helpers/series";
import { workspaceTestHelpers } from "./helpers/workspace";
import { conversationTestHelpers } from "./helpers/conversations";
import { notificationTestHelpers } from "./helpers/notifications";
import { contentTestHelpers } from "./helpers/content";
import { emailTestHelpers } from "./helpers/email";
import { ticketTestHelpers } from "./helpers/tickets";
import { aiTestHelpers } from "./helpers/ai";
import { cleanupTestHelpers } from "./helpers/cleanup";

export const createTestWorkspace: ReturnType<typeof internalMutation> = workspaceTestHelpers.createTestWorkspace;
export const updateTestHelpCenterAccessPolicy: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateTestHelpCenterAccessPolicy;
export const runSeriesEvaluateEnrollmentForVisitor: ReturnType<typeof internalMutation> = seriesTestHelpers.runSeriesEvaluateEnrollmentForVisitor;
export const runSeriesResumeWaitingForEvent: ReturnType<typeof internalMutation> = seriesTestHelpers.runSeriesResumeWaitingForEvent;
export const runSeriesProcessWaitingProgress: ReturnType<typeof internalMutation> = seriesTestHelpers.runSeriesProcessWaitingProgress;
export const getSeriesProgressForVisitorSeries: ReturnType<typeof internalMutation> = seriesTestHelpers.getSeriesProgressForVisitorSeries;
export const updateSeriesProgressForTest: ReturnType<typeof internalMutation> = seriesTestHelpers.updateSeriesProgressForTest;
export const createTestAuditLog: ReturnType<typeof internalMutation> = workspaceTestHelpers.createTestAuditLog;
export const createTestUser: ReturnType<typeof internalMutation> = workspaceTestHelpers.createTestUser;
export const createTestSessionToken: ReturnType<typeof internalMutation> = workspaceTestHelpers.createTestSessionToken;
export const createTestVisitor: ReturnType<typeof internalMutation> = conversationTestHelpers.createTestVisitor;
export const createTestConversation: ReturnType<typeof internalMutation> = conversationTestHelpers.createTestConversation;
export const createTestSurvey: ReturnType<typeof internalMutation> = contentTestHelpers.createTestSurvey;
export const expireTooltipAuthoringSession: ReturnType<typeof internalMutation> = contentTestHelpers.expireTooltipAuthoringSession;
export const completeTooltipAuthoringSession: ReturnType<typeof internalMutation> = contentTestHelpers.completeTooltipAuthoringSession;
export const createTestSeries: ReturnType<typeof internalMutation> = seriesTestHelpers.createTestSeries;
export const createTestPushCampaign: ReturnType<typeof internalMutation> = notificationTestHelpers.createTestPushCampaign;
export const sendTestPushCampaign: ReturnType<typeof internalMutation> = notificationTestHelpers.sendTestPushCampaign;
export const getTestPendingPushCampaignRecipients: ReturnType<typeof internalMutation> = notificationTestHelpers.getTestPendingPushCampaignRecipients;
export const createTestMessage: ReturnType<typeof internalMutation> = conversationTestHelpers.createTestMessage;
export const createTestPushToken: ReturnType<typeof internalMutation> = notificationTestHelpers.createTestPushToken;
export const createTestVisitorPushToken: ReturnType<typeof internalMutation> = notificationTestHelpers.createTestVisitorPushToken;
export const upsertTestNotificationPreference: ReturnType<typeof internalMutation> = notificationTestHelpers.upsertTestNotificationPreference;
export const upsertTestWorkspaceNotificationDefaults: ReturnType<typeof internalMutation> = notificationTestHelpers.upsertTestWorkspaceNotificationDefaults;
export const getTestMemberRecipientsForNewVisitorMessage: ReturnType<typeof internalMutation> = notificationTestHelpers.getTestMemberRecipientsForNewVisitorMessage;
export const getTestVisitorRecipientsForSupportReply: ReturnType<typeof internalMutation> = notificationTestHelpers.getTestVisitorRecipientsForSupportReply;
export const createTestInvitation: ReturnType<typeof internalMutation> = workspaceTestHelpers.createTestInvitation;
export const updateWorkspaceSettings: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateWorkspaceSettings;
export const upsertTestAutomationSettings: ReturnType<typeof internalMutation> = workspaceTestHelpers.upsertTestAutomationSettings;
export const cleanupTestData: ReturnType<typeof internalMutation> = cleanupTestHelpers.cleanupTestData;
export const cleanupE2ETestData: ReturnType<typeof internalMutation> = cleanupTestHelpers.cleanupE2ETestData;
export const createTestEmailConfig: ReturnType<typeof internalMutation> = emailTestHelpers.createTestEmailConfig;
export const createTestEmailConversation: ReturnType<typeof internalMutation> = emailTestHelpers.createTestEmailConversation;
export const createTestEmailMessage: ReturnType<typeof internalMutation> = emailTestHelpers.createTestEmailMessage;
export const createTestEmailThread: ReturnType<typeof internalMutation> = emailTestHelpers.createTestEmailThread;
export const createTestTicket: ReturnType<typeof internalMutation> = ticketTestHelpers.createTestTicket;
export const createTestTicketForm: ReturnType<typeof internalMutation> = ticketTestHelpers.createTestTicketForm;
export const createTestCollection: ReturnType<typeof internalMutation> = contentTestHelpers.createTestCollection;
export const createTestArticle: ReturnType<typeof internalMutation> = contentTestHelpers.createTestArticle;
export const publishTestArticle: ReturnType<typeof internalMutation> = contentTestHelpers.publishTestArticle;
export const updateTestArticle: ReturnType<typeof internalMutation> = contentTestHelpers.updateTestArticle;
export const removeTestArticle: ReturnType<typeof internalMutation> = contentTestHelpers.removeTestArticle;
export const createTestInternalArticle: ReturnType<typeof internalMutation> = contentTestHelpers.createTestInternalArticle;
export const publishTestInternalArticle: ReturnType<typeof internalMutation> = contentTestHelpers.publishTestInternalArticle;
export const createTestSnippet: ReturnType<typeof internalMutation> = contentTestHelpers.createTestSnippet;
export const createTestContentFolder: ReturnType<typeof internalMutation> = contentTestHelpers.createTestContentFolder;
export const createTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.createTestTour;
export const updateTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.updateTestTour;
export const removeTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.removeTestTour;
export const activateTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.activateTestTour;
export const deactivateTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.deactivateTestTour;
export const getTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.getTestTour;
export const listTestTours: ReturnType<typeof internalMutation> = contentTestHelpers.listTestTours;
export const duplicateTestTour: ReturnType<typeof internalMutation> = contentTestHelpers.duplicateTestTour;
export const getTestConversation: ReturnType<typeof internalMutation> = conversationTestHelpers.getTestConversation;
export const listTestConversations: ReturnType<typeof internalMutation> = conversationTestHelpers.listTestConversations;
export const updateTestConversationStatus: ReturnType<typeof internalMutation> = conversationTestHelpers.updateTestConversationStatus;
export const assignTestConversation: ReturnType<typeof internalMutation> = conversationTestHelpers.assignTestConversation;
export const markTestConversationAsRead: ReturnType<typeof internalMutation> = conversationTestHelpers.markTestConversationAsRead;
export const listTestMessages: ReturnType<typeof internalMutation> = conversationTestHelpers.listTestMessages;
export const sendTestMessageDirect: ReturnType<typeof internalMutation> = conversationTestHelpers.sendTestMessageDirect;
export const seedTestAIResponse: ReturnType<typeof internalMutation> = aiTestHelpers.seedTestAIResponse;
export const getTestWorkspaceFull: ReturnType<typeof internalMutation> = workspaceTestHelpers.getTestWorkspaceFull;
export const updateTestAllowedOrigins: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateTestAllowedOrigins;
export const updateTestSignupSettings: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateTestSignupSettings;
export const getTestAISettings: ReturnType<typeof internalMutation> = aiTestHelpers.getTestAISettings;
export const updateTestAISettings: ReturnType<typeof internalMutation> = aiTestHelpers.updateTestAISettings;
export const getTestVisitor: ReturnType<typeof internalMutation> = conversationTestHelpers.getTestVisitor;
export const addTestWorkspaceMember: ReturnType<typeof internalMutation> = workspaceTestHelpers.addTestWorkspaceMember;
export const listTestWorkspaceMembers: ReturnType<typeof internalMutation> = workspaceTestHelpers.listTestWorkspaceMembers;
export const updateTestMemberPermissions: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateTestMemberPermissions;
export const updateTestMemberRole: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateTestMemberRole;
export const removeTestMember: ReturnType<typeof internalMutation> = workspaceTestHelpers.removeTestMember;
export const removeTestWorkspaceMember: ReturnType<typeof internalMutation> = workspaceTestHelpers.removeTestWorkspaceMember;
export const cancelTestInvitation: ReturnType<typeof internalMutation> = workspaceTestHelpers.cancelTestInvitation;
export const acceptTestInvitation: ReturnType<typeof internalMutation> = workspaceTestHelpers.acceptTestInvitation;
export const listTestPendingInvitations: ReturnType<typeof internalMutation> = workspaceTestHelpers.listTestPendingInvitations;
export const simulateEmailWebhook: ReturnType<typeof internalMutation> = emailTestHelpers.simulateEmailWebhook;
export const getTestMessage: ReturnType<typeof internalMutation> = conversationTestHelpers.getTestMessage;
export const updateWorkspaceOrigins: ReturnType<typeof internalMutation> = workspaceTestHelpers.updateWorkspaceOrigins;
export const createTestConversationForVisitor: ReturnType<typeof internalMutation> = conversationTestHelpers.createTestConversationForVisitor;
export const lookupUserByEmail: ReturnType<typeof internalMutation> = workspaceTestHelpers.lookupUserByEmail;
export const lookupPendingInvitationsByEmail: ReturnType<typeof internalMutation> = workspaceTestHelpers.lookupPendingInvitationsByEmail;
