import { internalMutation } from "./_generated/server";
import { seedMutations } from "./testData/seeds";
import { cleanupMutations } from "./testData/cleanup";
import { demoWorkspaceMutations } from "./testData/demoWorkspace";
import { landingDemoMutations } from "./testData/landing";

export const seedTour: ReturnType<typeof internalMutation> = seedMutations.seedTour;
export const seedSurvey: ReturnType<typeof internalMutation> = seedMutations.seedSurvey;
export const seedCarousel: ReturnType<typeof internalMutation> = seedMutations.seedCarousel;
export const seedOutboundMessage: ReturnType<typeof internalMutation> = seedMutations.seedOutboundMessage;
export const seedArticles: ReturnType<typeof internalMutation> = seedMutations.seedArticles;
export const seedVisitor: ReturnType<typeof internalMutation> = seedMutations.seedVisitor;
export const seedSegment: ReturnType<typeof internalMutation> = seedMutations.seedSegment;
export const seedMessengerSettings: ReturnType<typeof internalMutation> = seedMutations.seedMessengerSettings;
export const seedAIAgentSettings: ReturnType<typeof internalMutation> = seedMutations.seedAIAgentSettings;
export const cleanupTestData: ReturnType<typeof internalMutation> = cleanupMutations.cleanupTestData;
export const seedAll: ReturnType<typeof internalMutation> = cleanupMutations.seedAll;
export const cleanupAll: ReturnType<typeof internalMutation> = cleanupMutations.cleanupAll;
export const clearAllTours: ReturnType<typeof internalMutation> = cleanupMutations.clearAllTours;
export const seedDemoData: ReturnType<typeof internalMutation> = demoWorkspaceMutations.seedDemoData;
export const getTourCount: ReturnType<typeof internalMutation> = cleanupMutations.getTourCount;
export const cleanupLandingDemo: ReturnType<typeof internalMutation> = landingDemoMutations.cleanupLandingDemo;
export const seedLandingDemo: ReturnType<typeof internalMutation> = landingDemoMutations.seedLandingDemo;
